<?php

namespace PP\CommentBundle\Entity;

/**
 * CommentThreadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentThreadRepository extends \Doctrine\ORM\EntityRepository
{
    
}
