<?php

namespace PP\ReportBundle\Entity;

/**
 * DisableTicketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DisableTicketRepository extends \Doctrine\ORM\EntityRepository
{
}
