<?php

namespace PP\ReportBundle\Entity;

/**
 * ReportReasonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReportReasonRepository extends \Doctrine\ORM\EntityRepository
{       
    
}
