<?php

namespace PP\ReportBundle\Entity;
use PP\ReportBundle\Constant\ReportTicketType;


/**
 * ReportTicketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReportTicketRepository extends \Doctrine\ORM\EntityRepository
{
    public function getTicketByType($type, $targetId){
             $qb = $this
                ->createQueryBuilder('rt')                
                ->where('rt.reportTicketType = :type')                
                ->setParameter('type', $type)
                ->andWhere('rt.targetId = :targetId')
                ->setParameter('targetId', $targetId)
                ->andWhere('rt.finished = false')
                ->orderBy('rt.createdDate', 'DESC')
                ->distinct(true)                
            ;
             
            return $qb
               ->getQuery()
               ->getResult()
            ;  
    }
        
}
