<?php

namespace PP\NotificationBundle\Entity;

/**
 * notificationFollowRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationFollowRepository extends \Doctrine\ORM\EntityRepository
{
    
    public function getNotifications($userId, $limit, $page){
        
        $qb = $this->createQueryBuilder('nf')
                        ->distinct(true)
                        ->leftJoin('nf.notificationThread', 'nfThread')
                        ->leftJoin('nfThread.user', 'u')                        
                        ->where('u.id = :userId')
                        ->setParameter('userId', $userId)
                
                        ->leftJoin('nf.followYou', 'fy')
                        ->addSelect('fy')
                        ->leftJoin('fy.profilImage', 'fyPI')
                        ->addSelect('fyPI')
                
                        ->orderBy('nf.createDate', 'DESC')                                                                 
                        ->setFirstResult(($page-1) * $limit)
                        ->setMaxResults($limit);
        ;
        
        return $qb
               ->getQuery()
               ->getResult()
        ;
    }
    
    public function getNotificationsNotViewed($userId){
        
        $qb = $this->createQueryBuilder('nf')
                        ->distinct(true)
                        ->leftJoin('nf.notificationThread', 'nfThread')
                        ->leftJoin('nfThread.user', 'u')                        
                        ->where('u.id = :userId')
                        ->setParameter('userId', $userId)
                        ->andWhere('nf.isViewed = false');                        
        
        return $qb
               ->getQuery()
               ->getResult()
        ;
    }
    
}
