<?php

namespace PP\NotificationBundle\Entity;

/**
 * notificationNewPropositionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationNewPropositionRepository extends \Doctrine\ORM\EntityRepository
{
    
    public function getNotifications($userId, $limit, $page){
        
        $qb = $this->createQueryBuilder('nNP')
                        ->distinct(true)
                        ->leftJoin('nNP.notificationThread', 'nfThread')
                        ->leftJoin('nfThread.user', 'u')                        
                        ->where('u.id = :userId')
                        ->setParameter('userId', $userId)                      
                                                                                        
                        ->leftJoin('nNP.proposition', 'nNPProp')
                        ->addSelect('nNPProp')
                        ->leftJoin('nNPProp.author', 'nNPPropAuth')
                        ->addSelect('nNPPropAuth')
                        ->leftJoin('nNPPropAuth.profilImage', 'nNPPropAuthPI')
                        ->addSelect('nNPPropAuthPI')
                        
                        ->orderBy('nNP.createDate', 'DESC')                                                                 
                        ->setFirstResult(($page-1) * $limit)
                        ->setMaxResults($limit);
        
        return $qb
               ->getQuery()
               ->getResult()
        ;
    }
    
}
