<?php

namespace PP\NotificationBundle\Entity;

/**
 * NotificationSelectedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationSelectedRepository extends \Doctrine\ORM\EntityRepository
{
}
