<?php

namespace PP\NotificationBundle\Entity;

/**
 * NotificationMessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationMessageRepository extends \Doctrine\ORM\EntityRepository
{
}
