<?php

namespace PP\RequestBundle\Entity;
use Doctrine\ORM\Tools\Pagination\Paginator;

use PP\RequestBundle\Constant\Constants;
/**
 * RequestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageRequestRepository extends \Doctrine\ORM\EntityRepository
{   
    public function getImageRequestByTag($tagId){
        $qb = $this->createQueryBuilder('ir')                        
                        ->distinct(true)
                        ->leftJoin('ir.tags', 't')
                        ->where("t.id = :tagId")                        
                         ->setParameter('tagId', $tagId);
        ;
        
        return $qb
               ->getQuery()
               ->getResult()
            ;  
    }
    
    public function getReportedImageRequest(){
        $qb = $this->createQueryBuilder('ir')                        
                        ->distinct(true)
                        ->leftJoin('ir.author', 'irA')
                        ->addSelect('irA')
                        ->where('ir.enabled = true')
                        ->andWhere('ir.reportNb > 0')
        ;
        
        return $qb
               ->getQuery()
               ->getResult()
            ;  
    }

    public function getIdBySlug($slug){
            $qb = $this->createQueryBuilder('ir')
                        ->select('ir.id')
                        ->where('ir.slug = :slug')
                        ->setParameter('slug', $slug);
            return  $qb
                        ->getQuery()
                        ->getSingleScalarResult();
        }
        
        public function getImageRequestsId($em, $searchParam, $limit, $page, $displayMode, $userId, $followingIds, $tagsParam = null, $categoriesParam = null, $concerningMeParam = false)
	{
             $qb = $this->createQueryBuilder('ir')
                        ->select('ir.id')
                        ->distinct(true)
                        ->leftJoin('ir.tags', 't')
                        ->leftJoin('ir.category', 'c')
                        ->leftJoin('ir.author', 'irA')
                        ->leftJoin('ir.propositions', 'p')
                        ->leftJoin('p.author', 'pA')
                        ->where('ir.enabled = true AND irA.enabled = true')
            ;
             
            if($searchParam != null){
                $qb = $qb
                        ->where($qb->expr()->like('ir.title', ':title'))
                        ->setParameter('title', '%'.$searchParam.'%')
                        ->orWhere($qb->expr()->like('t.name', ':name'))
                        ->setParameter('name', '%'.$searchParam.'%')
                        ->orWhere($qb->expr()->like('c.name', ':cat'))
                        ->setParameter('cat', '%'.$searchParam.'%');
                        
            }
            
            if($tagsParam != null){
                $i = 0;
                $request = '';
                foreach ($tagsParam as $tagName){
                    if($i>0)$request .= ' OR ';
                    $request .= 't.name = :nameT'.$i;
                    $qb = $qb                            
                            ->setParameter('nameT'.$i, $tagName);
                    $i++;                    
                }
                $qb = $qb
                            ->andWhere($request);
            }
            
            if($categoriesParam != null){
                $i = 0;
                $request = '';
                foreach ($categoriesParam as $cat){
                    if($i>0)$request .= ' OR ';
                    $request .= 'c.name = :nameC'.$i;
                    $qb = $qb                            
                            ->setParameter('nameC'.$i, $cat);
                    $i++;
                }
                 $qb = $qb
                            ->andWhere($request);
            }
            
            if($concerningMeParam){
                $qb = $qb
                        ->andWhere("irA.id = :userId2 OR pA.id = :userId2")
                        ->setParameter('userId2', $userId);
            }
            
            if($displayMode == Constants::ORDER_BY_DATE){
                $qb = $qb->orderBy('ir.createdDate', 'DESC'); 
            }else if($displayMode == Constants::ORDER_BY_UPVOTE){
                $qb = $qb->orderBy('ir.upvote + (ir.propositionsNb*2)', 'DESC'); 
            }else if($displayMode == Constants::ORDER_BY_INTEREST){
                $qb = $qb                                               
                        ->from('PPUserBundle:User', 'u')                        
                        ->andwhere('u.id = :userId')                        
                        ->setParameter('userId', $userId)                        
                        ->leftJoin('u.following', 'uF')                       
                        ->andwhere("irA.id IN(:followingIds) AND irA.enabled = true")
                        ->setParameter('followingIds', array_values($followingIds))
                        ->orderBy('ir.createdDate', 'DESC'); 
                ;
            }
            
            $qb = $qb
                      ->setFirstResult(($page-1) * $limit)
                      ->setMaxResults($limit)
            ;
             
            return $qb
               ->getQuery()
               ->getResult()
            ;           		  
	}
                        
    	public function getOneImageRequest($id)
	{
            $qb = $this
                ->createQueryBuilder('ir')
                ->where('ir.id = :id')
                ->setParameter('id', $id)
                ->leftJoin('ir.author', 'irA')
                ->addSelect('irA')
                ->leftJoin('ir.category', 'c')
                ->addSelect('c')
                ->leftJoin('ir.tags', 't')                
                ->addSelect('t')                
            ;                                    
          
	  return $qb
		->getQuery()
		->getSingleResult()
	  ;
	}
        
        /* query for profile page */
        
        public function getUserImageRequestContributionIds($userid, $limit, $page){
             $qb = $this
                ->createQueryBuilder('ir')
                ->select('ir.id')
                ->where('ir.enabled = true')
                ->andWhere('ir.author = :userId')                
                ->leftJoin('ir.propositions', 'p')
                ->orWhere('p.author = :userId')
                ->setParameter('userId', $userid)
                ->orderBy('ir.createdDate', 'DESC')
                ->distinct(true)                
            ;
             
            $qb = $qb
                   ->setFirstResult(($page-1) * $limit)
                   ->setMaxResults($limit)
               ;
            return $qb
               ->getQuery()
               ->getResult()
            ;  
        }
        
        public function getPopularImageRequests($limit){
            $today = new \DateTime();         
            $lastWeek = new \DateTime();        
            $lastWeek->sub(new \DateInterval('P7D'));         

            $qb = $this->createQueryBuilder('ir')
                        ->distinct(true)
                        ->leftJoin('ir.author', 'irA')
                        ->addSelect('irA')
                        ->where('ir.createdDate BETWEEN :lastWeek AND :today' )                        
                        ->setParameter('lastWeek', $lastWeek)
                        ->setParameter('today', $today)
                        ->andWhere('irA.enabled = true')
                        ->addOrderBy('ir.upvote + ir.propositionsNb', 'DESC')
                        ->setMaxResults($limit)
        ; 
        return  $qb
                           ->getQuery()
                           ->getResult(); 
        }
    
}
