<?php

namespace PP\RequestBundle\Entity;

/**
 * PopularRequestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PopularTagRepository extends \Doctrine\ORM\EntityRepository
{    
    public function getPopularTags($limit){
        
        $qb = $this->createQueryBuilder('pt')
                ->distinct(true)
                ->leftJoin('pt.tag', 't')                       
                ->setMaxResults($limit)
        ; 
        return  $qb
                ->getQuery()
                ->getResult(); 
    }
    
}
