<?php

namespace PP\RequestBundle\Entity;

use Symfony\Component\Validator\Constraints\DateTime;
/**
 * TagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagRepository extends \Doctrine\ORM\EntityRepository
{
   
   public function getPopularTags($limit){
        $today = new \DateTime();         
        $lastWeek = new \DateTime();        
        $lastWeek->sub(new \DateInterval('P7D'));
        
        $qb = $this->createQueryBuilder('t')
                    ->distinct(true)
                    ->leftJoin('t.imageRequests', 'ir')
                    ->where('ir.createdDate BETWEEN :lastWeek AND :today')
                    ->setParameter('lastWeek', $lastWeek)
                    ->setParameter('today', $today)
                    ->orderBy('t.usedNb', 'DESC')
                    ->setMaxResults($limit)
        ; 
         return  $qb
                           ->getQuery()
                           ->getResult();
   }
   
    public function geTagByName($name){
           $qb = $this->createQueryBuilder('t')                        
                       ->where('t.name = :name')
                       ->setParameter('name', $name);
           ;  

           try{
               return  $qb
                           ->getQuery()
                           ->getSingleResult();
           }catch(\Doctrine\ORM\NoResultException $e){
               return null;
           }
    }
}
