<?php

namespace PP\MessageBundle\Entity;

/**
 * MessageThreadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageThreadRepository extends \Doctrine\ORM\EntityRepository
{
    public function getConversation($threadId, $limit, $page){
        $qb = $this->createQueryBuilder('mThread')                                              
                        ->leftJoin('mThread.messages', 'm')
                        ->leftJoin('m.author', 'mA')
                        ->leftJoin('m.target', 'mT')
                        ->where('mThread.id = :threadId')
                        ->setParameter('threadId', $threadId)                        
                        ->addSelect('m')
                        ->addSelect('mA')
                        ->addSelect('mT')
                        ->orderBy('m.createdDate', 'DESC');
        
         $qb = $qb
                      ->setFirstResult(($page-1) * $limit)
                      ->setMaxResults($limit)
            ;   
        
        try{
            $result = $qb
                    ->getQuery()
                    ->getSingleResult();
            return $result;
            
        } catch (\Doctrine\ORM\NoResultException $ex) {            
            return null;
        }
    }
    
     
}
